name: Step 6, Add Agent and Tools

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/webapi/agentService.js"
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_agent_directory:
    name: On addition of an agentService module
    needs: get_current_step

    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 6 }}

    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository to verify the agent directory exists
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches

      - name: Check agentService.js file exists
        id: check_agent
        run: |
          if [ -f "packages/webapi/agentService.js" ]; then
            echo "agent_exists=true" >> $GITHUB_OUTPUT
          else
            echo "agent_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Update to step 7
        if: steps.check_agent.outputs.agent_exists == 'true'
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 6
          to_step: 7